### ISSUE TITLE
Updating Elements Errors

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleElements#17]
Feedback from Arup (via @daviddekoning & arup): 
> Members that did come in via Speckle Revit client did not always update framing. Only updated members that were on grids. Did not delete off grid elements (ie, they were doubling up)!

**Comment by teocomi** [comment]
Was an application id being passed? How were the members associated with the grid?

**Comment by teocomi** [comment]
Closing until further info is provided.
