### ISSUE TITLE
How do I access Revit Element Id in Speckle?

### ISSUE THREAD

**Issue by htlcnn** [speckleworks/SpeckleElements#21]
I have a speckle stream running on hestia. When I select an element, I can get many of its properties/attribues, but I can not get Revit Element Id, just Revit Element UUID (`"_id"` or `properties["id"]` in Speckle). This makes collaborating between Speckle viewer and Revit modeller a little struggling. Despite that I can use Revit API to `doc.GetElement(str_guid)` to retrieve correspond element in Revit, I think it would be better if we could have Revit Element Id in Speckle's attributes.
![image](https://user-images.githubusercontent.com/931924/76694353-3484a780-66a4-11ea-8dcb-54a4409a50e7.png)

**Comment by htlcnn** [comment]
Element's `UniqueId` (current `_id`/`properties["id"]` attribute of SpeckleElement) is unique across all Revit projects. `ElementId` is unique in 1 project only, but it's handy when collaborating. If possible, please make them `element_id` and `unique_id` in addition to current implementation.
Thanks.

**Comment by htlcnn** [comment]
I've compared `_id`/`properties["id"]` of SpeckleElement to Revit Element's UniqueId. They're different from each other.
Is the `_id` set [here](https://github.com/speckleworks/SpeckleRevitReboot/blob/master/SpeckleRevitReboot/UI/Sender.cs#L160)?

**Comment by didimitrie** [comment]
Not sure, but I don't think so - I think the original revit unique id is captured in the [parameters step here](https://github.com/speckleworks/SpeckleElements/blob/master/SpeckleElementsRevit/ConversionsBase.cs#L87). 

I'll ping @teocomi so he join in on this conversation, as he's been working on this repo more recently than me. 

> please make them element_id and unique_id in addition to current implementation.

We can add as well the other id property too, and leave the old one unchanged as it is (backwards compatibility).

**Comment by teocomi** [comment]
Hey @htlcnn !
It would help us if you could explain how you'd use the ElementId and why the UniqueId is not fit for purpose? As Dimitrie mentioned, the ElementId can change with simple Save To Central operations, so it's not best to rely on it...

**Comment by htlcnn** [comment]
Revit has a Button at Manage -> Inquiry -> Select By Id. It receives ElementIds separated by space, comma, semi-colon. If I use Speckle Viewer to check the model and detect a modelling error, it would be easier for me to ask the modeler to fix the elements that match ElementIds I got from Speckle. If I give him UniqueIds, he has no existing tool to select corresponding elements.

[Revit Developer's Guide](http://help.autodesk.com/view/RVT/2020/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Introduction_Elements_Essentials_General_Properties_html) says UniqueId is unique between all projects, ElementId is unique within a project. So I think as long as it is still the same project (local or central), ElementId doesn't change. I've checked several elements randomly, ElementIds didn't change even when I detached to a new model (either keep or discard worksets). Local file's ElementId and Central file's ElementId of identical elements are the same.

**Comment by teocomi** [comment]
Gotcha! I assumed it was for use with "Select By Id". 
We'll add ElementId to the properties being harvested, so just stay tuned on this issue...

In the future ideally we could provide a native Speckle way to do so, rather than having to manually copy/paste IDs... :)

**Comment by htlcnn** [comment]
Great! I think a Speckle way might be adding a *Copy selected elements to clipboard* button in SpeckleViewer. I'm new to Vue and trying to understand how SpeckleAdmin works.

**Comment by teocomi** [comment]
Available from the next release!

**Comment by htlcnn** [comment]
@teocomi you're awesome!
