### ISSUE TITLE
Add Type Parameters to GetElementParams

### ISSUE THREAD

**Issue by htlcnn** [speckleworks/SpeckleElements#26]
Hi,
I'm proposing to add type parameters of elements when converting from Revit to Speckle. Because of the classification hierarchy in Revit, I think one type's parameters are also consider attributes of all of its instances (Autodesk made type parameters schedulable).
If I'm not misreading, type parameters could be added here:
https://github.com/speckleworks/SpeckleElements/blob/89fea2d40a190fd5281f9db9bec97680968b4ae0/SpeckleElementsRevit/ConversionsBase.cs#L88
If this proposal was accepted, I would try to use my poor C# skill to submit a PR.
Thanks.

**Comment by didimitrie** [comment]
Sorry for the delay. I'll ping @teocomi on this one too. I think it's a good idea, as long as it won't break backwards compatibility. Mostly thinking when getting those elements back into revit, the standard route will try and set those type params?

**Comment by teocomi** [comment]
Yup, sorry I realized I wasn't watching this repo!

@htlcnn I think that'd be a useful feature, and it shouldn't cause issue when bringing stuff back to Revit **unless** there are instance parameters with the same name... 
How were you planning to extract type parameters? Don't think I've done this before!

**Comment by htlcnn** [comment]
@teocomi for distinguishing instance parameters from type parameters, I think we could add a new key to `properties`. `type_parameters` might be a good key name.

**Comment by didimitrie** [comment]
@htlcnn, as a style guide reference, would use camelCase - so maybe `typeParameters`? That aside, keen to continue the discussion in a future PR if you want to go ahead :)
